/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analyses */
        get: operations["analyses_api_v1_analyses_get"];
        put?: never;
        /** Analyze Request */
        post: operations["analyze_request_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis */
        get: operations["analysis_api_v1_analyses__identifier__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{identifier}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact */
        get: operations["artifact_api_v1_artifacts__identifier__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiments */
        get: operations["experiments_api_v1_experiments_get"];
        put?: never;
        /** Experiment Create */
        post: operations["experiment_create_api_v1_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiment */
        get: operations["experiment_api_v1_experiments__identifier__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Files */
        get: operations["files_api_v1_files_get"];
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{identifier}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_api_v1_files__identifier__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_v1_jobs__identifier__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{identifier}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_jobs__identifier__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profiles */
        get: operations["profiles_api_v1_profiles_get"];
        put?: never;
        /** Profile Create */
        post: operations["profile_create_api_v1_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Profile Import */
        post: operations["profile_import_api_v1_profiles_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{identifier}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Profile Revision */
        post: operations["profile_revision_api_v1_profiles__identifier__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{identifier}/revisions/{revision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_v1_profiles__identifier__revisions__revision__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{identifier}/revisions/{revision}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile Export */
        get: operations["profile_export_api_v1_profiles__identifier__revisions__revision__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{identifier}/revisions/{revision}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Profile Publish */
        post: operations["profile_publish_api_v1_profiles__identifier__revisions__revision__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{identifier}/revisions/{revision}/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile States */
        get: operations["profile_states_api_v1_profiles__identifier__revisions__revision__states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** APIError */
        APIError: {
            /** Code */
            code: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Field */
            field: string | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** AnalysisInput */
        AnalysisInput: {
            /** Branch */
            branch?: ("program" | "erase") | null;
            /** Column Mapping */
            column_mapping: {
                [key: string]: string;
            };
            /** Condition Id */
            condition_id: string;
            /** Device Id */
            device_id: string;
            /** Direction */
            direction?: ("ltp" | "ltd") | null;
            /**
             * File Id
             * Format: uuid
             */
            file_id: string;
            /** Read Vgs V */
            read_vgs_v?: number | null;
            /** Row End */
            row_end?: number | null;
            /** Row Start */
            row_start?: number | null;
            /** Sheet */
            sheet?: string | null;
            /** Source Label */
            source_label?: string | null;
            /** Sweep Amplitude V */
            sweep_amplitude_v?: number | null;
            /** Units */
            units: {
                [key: string]: string;
            };
            /** Vds V */
            vds_v?: number | null;
        };
        /** AnalysisList */
        AnalysisList: {
            /** Items */
            items: components["schemas"]["AnalysisResult"][];
        } & {
            [key: string]: unknown;
        };
        /** AnalysisRequest */
        AnalysisRequest: {
            /** Inputs */
            inputs: components["schemas"]["AnalysisInput"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "iv" | "d2d" | "retention" | "pulse_states";
            /** Settings */
            settings?: {
                [key: string]: unknown;
            };
        };
        /** AnalysisResult */
        AnalysisResult: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Artifacts */
            artifacts: components["schemas"]["Artifact"][];
            /** Condition Id */
            condition_id?: string | null;
            /** Exclusions */
            exclusions?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Kind */
            kind?: ("iv" | "d2d" | "retention" | "pulse_states") | null;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** Summaries */
            summaries?: {
                [key: string]: unknown;
            } | null;
            /** Tables */
            tables?: {
                [key: string]: {
                    [key: string]: unknown;
                }[];
            } | null;
            /** Warnings */
            warnings?: string[] | null;
        } & {
            [key: string]: unknown;
        };
        /** Artifact */
        Artifact: {
            /** Download Url */
            download_url: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Media Type */
            media_type: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        } & {
            [key: string]: unknown;
        };
        /** Assumption */
        Assumption: {
            /** Description */
            description: string;
            /**
             * Evidence Kind
             * @enum {string}
             */
            evidence_kind: "measured" | "derived" | "assumed";
            /** Id */
            id: string;
            /** Source Ref */
            source_ref: string | null;
        };
        /** Body_profile_import_api_v1_profiles_import_post */
        Body_profile_import_api_v1_profiles_import_post: {
            /** File */
            file: string;
        };
        /** Body_upload_api_v1_files_post */
        Body_upload_api_v1_files_post: {
            /** Files */
            files: string[];
        };
        /** C2C */
        C2C: {
            /** Cv */
            cv: null;
            /**
             * Reason
             * @constant
             */
            reason: "not_provided";
            /**
             * Status
             * @constant
             */
            status: "unavailable";
        };
        /** Capabilities */
        Capabilities: {
            /** Effects */
            effects: {
                [key: string]: components["schemas"]["Capability"];
            };
            /** Engines */
            engines: {
                [key: string]: components["schemas"]["Capability"];
            };
            hardware: components["schemas"]["HardwareControls"];
            /** Limits */
            limits: {
                [key: string]: number;
            };
            /** Models */
            models: {
                [key: string]: components["schemas"]["Capability"];
            };
            /** Profile Schema Version */
            profile_schema_version: string;
            /** Schema Version */
            schema_version: string;
            /** Supported File Formats */
            supported_file_formats: string[];
            /** Warnings */
            warnings: string[];
        };
        /** Capability */
        Capability: {
            /** Available */
            available: boolean;
            /** Config */
            config?: string | null;
            /** Parity */
            parity?: {
                [key: string]: unknown;
            } | null;
            /** Reason */
            reason: string | null;
            /** Version */
            version?: string | null;
        };
        /** D2D */
        D2D: {
            /** Analysis Id */
            analysis_id: string | null;
            /** Assumption Ids */
            assumption_ids: string[];
            /** Cv */
            cv: number | null;
            /**
             * Distribution
             * @constant
             */
            distribution: "assumed_lognormal";
            /** Matched Conditions */
            matched_conditions: number;
            /**
             * Physical Device Count
             * @constant
             */
            physical_device_count: 2;
            /** Reason */
            reason?: string | null;
            /**
             * Source Kind
             * @constant
             */
            source_kind: "iv_proxy";
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "unavailable";
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["APIError"];
        };
        /** ExperimentList */
        ExperimentList: {
            /** Items */
            items: components["schemas"]["ExperimentResult"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * CTFM first-release experiment request v1.2.0/v1.3.0
         * @description Validated request shape; server must also enforce published profile/data/engine capabilities and run budget. No measured device fields may be overridden. v1.1.0 requests are not reinterpreted: tile_size is now explicit with the ADC off and adc_order is required, so a 1.1.0 request is rejected with an explicit migration error. v1.2.0 requests keep their original meaning (C2C unavailable, single write). v1.3.0 adds an optional manual-assumption C2C model per docs/completion-plan-2026-09-21.md P2: relative CV in percent per referenced profile revision, plus 1-100 reprogram iterations; off (the default reading of a 1.2.0 request) is unchanged.
         */
        ExperimentRequest: {
            arrays: number;
            /** Format: uuid */
            checkpoint_id: string | null;
            effects: {
                adc: boolean;
                c2c: boolean;
                d2d: boolean;
                retention: boolean;
            };
            engines: {
                /** @enum {unknown} */
                accuracy: "torch_reference" | "aihwkit_ideal";
                /** @constant */
                ppa: "off";
            };
            hardware: {
                /** @enum {unknown} */
                adc_bits: null | 3 | 4 | 5 | 6 | 7 | 8;
                /** @enum {unknown} */
                adc_order: null | "subtract_then_adc" | "adc_then_subtract";
                preset_id: unknown;
                /** @enum {unknown} */
                range_policy: null | "validation_max_abs";
                /** @enum {unknown} */
                tile_size: 64 | 128 | 256;
            };
            mappings: ("fixed_reference" | "pair_search")[];
            /** @constant */
            model_id: "mnist_mlp_v1";
            n_reprogram: number;
            pools: ("combined" | "ltp" | "ltd" | "common")[];
            profile_refs: {
                /** @description Manual engineering assumption (not a measured CTFM distribution): relative CV as a percent, converted to a ratio exactly once at this boundary (ctfm.simulation.math.c2c_relative_cv_percent_to_ratio). */
                c2c?: {
                    cv_percent: number;
                    /** @constant */
                    source: "manual_assumption";
                };
                /** Format: uuid */
                id: string;
                revision: number;
            }[];
            /** @enum {unknown} */
            schema_version: "1.2.0" | "1.3.0";
            seed: number;
            years: number[];
        } & (unknown & unknown & unknown & unknown & unknown & unknown);
        /** ExperimentResult */
        ExperimentResult: {
            /** Artifacts */
            artifacts: components["schemas"]["Artifact"][];
            /** Assumptions */
            assumptions?: {
                [key: string]: unknown;
            }[] | null;
            /** Effective Config */
            effective_config?: {
                [key: string]: unknown;
            } | null;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            } | null;
            /** Requested Config */
            requested_config?: {
                [key: string]: unknown;
            } | null;
            /** Resolved Config */
            resolved_config?: {
                [key: string]: unknown;
            } | null;
            /** Runs */
            runs?: components["schemas"]["RunResult"][] | null;
            /** Schema Version */
            schema_version?: ("1.2.0" | "1.3.0") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "partial" | "failed" | "cancelled";
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
            /** Warnings */
            warnings?: string[] | null;
        } & {
            [key: string]: unknown;
        };
        /** Extraction */
        Extraction: {
            /** Crossing Segments */
            crossing_segments: {
                [key: string]: unknown;
            };
            /** Excluded Conditions */
            excluded_conditions: {
                [key: string]: unknown;
            };
            /** Exclusions */
            exclusions: {
                [key: string]: unknown;
            }[];
            import_origin?: components["schemas"]["ImportOrigin"] | null;
            /** Iref A */
            iref_a: number;
            /**
             * Parser Version
             * @constant
             */
            parser_version: "1.0.0";
            /** Read Tolerance V */
            read_tolerance_v: number;
            /** Read Vgs V */
            read_vgs_v: number;
            /** Retention Start Time S */
            retention_start_time_s: number;
            /**
             * Sample Offset Rows
             * @constant
             */
            sample_offset_rows: 2;
            /** Start Time S */
            start_time_s: number;
            /** Vds V */
            vds_v: number;
            /** Write Threshold V */
            write_threshold_v: number;
        };
        /** FileList */
        FileList: {
            /** Items */
            items: components["schemas"]["FileMetadata"][];
        } & {
            [key: string]: unknown;
        };
        /** FileMetadata */
        FileMetadata: {
            /** Created At */
            created_at: string;
            /**
             * File Id
             * Format: uuid
             */
            file_id: string;
            /** Media Type */
            media_type: string;
            /** Name */
            name: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        } & {
            [key: string]: unknown;
        };
        /** FilePreview */
        FilePreview: {
            /** Columns */
            columns: string[];
            /**
             * File Id
             * Format: uuid
             */
            file_id: string;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Sheet */
            sheet: string | null;
            /** Sheets */
            sheets: string[];
            /** Source Rows */
            source_rows: number[];
            /** Warnings */
            warnings: string[];
        } & {
            [key: string]: unknown;
        };
        /** FileUploadResult */
        FileUploadResult: {
            /** Files */
            files: components["schemas"]["FileMetadata"][];
        } & {
            [key: string]: unknown;
        };
        /** HardwareControls */
        HardwareControls: {
            /** Adc Bits */
            adc_bits: number[];
            /** Adc Orders */
            adc_orders: string[];
            /** Range Policies */
            range_policies: string[];
            /** Tile Sizes */
            tile_sizes: number[];
            /** Validated Combinations */
            validated_combinations: {
                [key: string]: unknown;
            }[];
        };
        /** ImportOrigin */
        ImportOrigin: {
            /** Profile Hash */
            profile_hash: string;
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /** Revision */
            revision: number;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published";
        };
        /** JobList */
        JobList: {
            /** Items */
            items: components["schemas"]["JobResult"][];
        } & {
            [key: string]: unknown;
        };
        /** JobResult */
        JobResult: {
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Completed */
            completed: number;
            /** Created At */
            created_at: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "analysis" | "experiment";
            /** Progress */
            progress: number;
            /** Stage */
            stage: string | null;
            /** Started At */
            started_at: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** Total */
            total: number;
        } & {
            [key: string]: unknown;
        };
        /** Measurement */
        Measurement: {
            /**
             * Applied Pulse Count
             * @default 512
             */
            applied_pulse_count: number;
            /**
             * Interval S
             * @default 0.001
             */
            interval_s: number;
            /**
             * Pulse Width S
             * @default 0.001
             */
            pulse_width_s: number;
            /**
             * Read Vgs V
             * @default 0
             */
            read_vgs_v: number;
            /**
             * Saturation Verified
             * @default false
             */
            saturation_verified: boolean;
            /**
             * Vds V
             * @default 0.1
             */
            vds_v: number;
        };
        /** Pool */
        Pool: {
            /** Available */
            available: boolean;
            /** Common Hi S */
            common_hi_s?: number | null;
            /** Common Lo S */
            common_lo_s?: number | null;
            /** G Max S */
            g_max_s: number | null;
            /** G Min S */
            g_min_s: number | null;
            /** Reason */
            reason: string | null;
            /** State Ids */
            state_ids: string[];
        };
        /** ProfileCreate */
        ProfileCreate: {
            /** Condition Id */
            condition_id: string;
            /** D2D Analysis Id */
            d2d_analysis_id?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Retention Analysis Id */
            retention_analysis_id?: string | null;
            /** Selected State Ids */
            selected_state_ids: string[];
            /**
             * State Analysis Id
             * Format: uuid
             */
            state_analysis_id: string;
        };
        /** ProfileManifest */
        ProfileManifest: {
            /** Assumptions */
            assumptions: components["schemas"]["Assumption"][];
            c2c: components["schemas"]["C2C"];
            /** Condition Id */
            condition_id: string;
            /** Created At */
            created_at: string;
            d2d: components["schemas"]["D2D"];
            /** Display Name */
            display_name: string;
            extraction: components["schemas"]["Extraction"];
            measurement: components["schemas"]["Measurement"];
            /** Pools */
            pools: {
                [key: string]: components["schemas"]["Pool"];
            };
            /** Profile Hash */
            profile_hash: string;
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /** Published At */
            published_at: string | null;
            retention: components["schemas"]["Retention"];
            review: components["schemas"]["Review"];
            /** Revision */
            revision: number;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0.0";
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
            /**
             * States File
             * @constant
             */
            states_file: "states.csv";
            /** States Sha256 */
            states_sha256: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published";
        };
        /** ProfilePublish */
        ProfilePublish: {
            /** Review Note */
            review_note: string;
            /** Reviewer */
            reviewer: string;
        };
        /** ProfileRevision */
        ProfileRevision: {
            /** Base Revision */
            base_revision: number;
            /** Display Name */
            display_name?: string | null;
            /** Selected State Ids */
            selected_state_ids?: string[] | null;
        };
        /** QueuedAnalysis */
        QueuedAnalysis: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** QueuedExperiment */
        QueuedExperiment: {
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** Retention */
        Retention: {
            /** Analysis Id */
            analysis_id: string | null;
            /** Current Basis */
            current_basis?: "raw" | null;
            erase_fit: components["schemas"]["RetentionFit"] | null;
            program_fit: components["schemas"]["RetentionFit"] | null;
            /** Program Reference Current A */
            program_reference_current_a?: number | null;
            /** Read Vgs V */
            read_vgs_v: number | null;
            /** Reason */
            reason?: string | null;
            /** Reference Time S */
            reference_time_s?: number | null;
            /** Simulation Available */
            simulation_available?: boolean | null;
            /** Source Label */
            source_label: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "unavailable";
            /** Vds V */
            vds_v: number | null;
        };
        /** RetentionFit */
        RetentionFit: {
            /** A */
            a: number;
            /**
             * A Unit
             * @default A
             * @constant
             */
            a_unit: "A";
            /** B */
            b: number;
            /**
             * B Unit
             * @default A/decade
             * @constant
             */
            b_unit: "A/decade";
            /** N */
            n: number;
            /** R Squared */
            r_squared: number | null;
            /** Rmse */
            rmse: number;
            /** Time Max S */
            time_max_s: number;
            /** Time Min S */
            time_min_s: number;
        };
        /** Review */
        Review: {
            /** Note */
            note?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Reviewer */
            reviewer?: string | null;
        };
        /** RunResult */
        RunResult: {
            /** Accuracy */
            accuracy?: number | null;
            /** Array Index */
            array_index?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "D0" | "D1" | "M0" | "ALL" | "candidate";
            /** Loss Vs Digital Pp */
            loss_vs_digital_pp?: number | null;
            /** Loss Vs Mapped Pp */
            loss_vs_mapped_pp?: number | null;
            /** Reason */
            reason?: string | null;
            /** Reprogram Index */
            reprogram_index?: number | null;
            /** Retention Loss Pp */
            retention_loss_pp?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "succeeded" | "invalid" | "skipped" | "failed";
            /** Years */
            years?: number | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyses_api_v1_analyses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyze_request_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedAnalysis"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analysis_api_v1_analyses__identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    artifact_api_v1_artifacts__identifier__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    experiments_api_v1_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    experiment_create_api_v1_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedExperiment"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    experiment_api_v1_experiments__identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    files_api_v1_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_api_v1_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v1_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview_api_v1_files__identifier__preview_get: {
        parameters: {
            query?: {
                sheet?: string | null;
            };
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilePreview"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    jobs_api_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    job_api_v1_jobs__identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_api_v1_jobs__identifier__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profiles_api_v1_profiles_get: {
        parameters: {
            query?: {
                status?: ("draft" | "published") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_create_api_v1_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileManifest"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_import_api_v1_profiles_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_profile_import_api_v1_profiles_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileManifest"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_revision_api_v1_profiles__identifier__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRevision"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileManifest"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_api_v1_profiles__identifier__revisions__revision__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileManifest"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_export_api_v1_profiles__identifier__revisions__revision__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_publish_api_v1_profiles__identifier__revisions__revision__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePublish"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileManifest"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_states_api_v1_profiles__identifier__revisions__revision__states_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
