import {useEffect,useState,type ReactNode} from 'react';
import {api,ApiError,type Artifact,type Job,type PpaSummary,type Row} from './lib/api';
export const show=(v:unknown):string=>v===null||v===undefined?'—':typeof v==='object'?JSON.stringify(v):String(v);
export const errorText=(error:unknown)=>error instanceof Error?error.message:typeof error==='object'&&error!==null&&'message'in error?String(error.message):show(error);
export function ErrorNotice({error,retry}:{error:unknown;retry?:()=>void}){return error?<div role="alert" className="notice error"><strong>요청을 완료하지 못했습니다.</strong><div>{errorText(error)}</div>{error instanceof ApiError&&error.field&&<small>입력 항목: {error.field}</small>}{error instanceof ApiError&&error.requestId&&<small>요청 ID: {error.requestId}</small>}{retry&&<button type="button" onClick={retry}>다시 시도</button>}</div>:null;}
export function useResource<T>(path:string|null){const[data,setData]=useState<T|null>(null);const[error,setError]=useState<unknown>(null);const[loading,setLoading]=useState(false);const[tick,setTick]=useState(0);useEffect(()=>{if(!path){setData(null);return;}let active=true;setData(null);setLoading(true);setError(null);api.get<T>(path).then(v=>{if(active)setData(v);}).catch(e=>{if(active)setError(e);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[path,tick]);return{data,error,loading,reload:()=>setTick(n=>n+1)};}
export function Heading({eyebrow,title,children}:{eyebrow:string;title:string;children?:ReactNode}){return <header className="page-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{children&&<p>{children}</p>}</header>;}
export function Panel({title,children,aside}:{title:string;children:ReactNode;aside?:ReactNode}){return <section className="panel"><div className="panel-heading"><h2>{title}</h2>{aside}</div>{children}</section>;}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function Status({value}:{value:string}){return <span className={'status '+value}>{({queued:'대기',running:'실행 중',succeeded:'완료',failed:'실패',cancelled:'취소',draft:'초안',published:'발행',partial:'부분 완료',skipped:'건너뜀',invalid:'유효하지 않음'} as Record<string,string>)[value]||value}</span>;}
export function JsonDetails({title,value,open=false}:{title:string;value:unknown;open?:boolean}){return <details open={open}><summary>{title}</summary><pre>{JSON.stringify(value,null,2)}</pre></details>;}
export function DataTable({rows,columns,caption}:{rows:Row[];columns?:string[];caption?:string}){const[limit,setLimit]=useState(100);const keys=columns||Array.from(new Set(rows.flatMap(Object.keys)));if(!rows.length)return <p className="empty">표시할 데이터가 없습니다.</p>;return <><div className="table-scroll"><table>{caption&&<caption>{caption}</caption>}<thead><tr>{keys.map(k=><th key={k} scope="col">{k}</th>)}</tr></thead><tbody>{rows.slice(0,limit).map((row,i)=><tr key={i}>{keys.map(k=><td key={k} title={show(row[k])}>{show(row[k])}</td>)}</tr>)}</tbody></table></div>{rows.length>limit&&<button className="subtle" type="button" onClick={()=>setLimit(n=>n+100)}>100행 더 보기 ({Math.min(limit,rows.length)}/{rows.length})</button>}</>;}
export function Notices({items,title='경고 및 안내'}:{items?:unknown[];title?:string}){if(!items?.length)return null;return <div className="notice"><strong>{title}</strong><ul>{items.map((item,i)=><li key={i}>{show(item)}</li>)}</ul></div>;}
export function PpaPanel({ppa}:{ppa?:PpaSummary|null}){
 if(!ppa)return null;
 const numeric:[string,number|null|undefined][]=[['면적 m²',ppa.area_m2],['에너지 J/추론',ppa.energy_j_per_inference],['지연 s/추론',ppa.latency_s_per_inference]];
 return <div className="ppa-panel"><div className="result-title"><h4>PPA (면적·에너지·지연)</h4><Status value={ppa.status}/></div>
  <DataTable caption="미실행 값은 0이 아니라 —입니다" rows={[Object.fromEntries(numeric.map(([k,v])=>[k,v==null?null:v]))]}/>
  <Notices items={ppa.reasons} title="PPA를 실행하지 않은 이유"/>
  {ppa.preset?.preset_id?<p className="muted">preset <code>{ppa.preset.preset_id}</code>{ppa.preset_artifact?.sha256?` · ${ppa.preset_artifact.sha256.slice(0,12)}`:''}</p>
   :<p className="muted">검증된 CTFM 등가 회로 preset이 없습니다. 아래 차이는 정확도 모델과 엔진 회로 모델이 구조적으로 다른 지점입니다.</p>}
  {ppa.model_mismatches?.length?<DataTable caption="정확도 모델과 PPA 엔진 모델의 차이" rows={ppa.model_mismatches.map(m=>({id:m.id,내용:m.detail}))}/>:null}
  <JsonDetails title="PPA 상세 · 엔진 빌드 · preset 판정" value={ppa}/></div>;
}
export function Downloads({items}:{items?:Artifact[]}){return items?.length?<div className="downloads">{items.map(a=><a key={a.id} href={a.download_url||`/api/v1/artifacts/${a.id}/download`} download>{a.filename}<span>↓</span></a>)}</div>:<p className="muted">아직 생성된 다운로드 파일이 없습니다.</p>;}
export function JobProgress({id,onDone}:{id:string|null;onDone:()=>void}){const[job,setJob]=useState<Job|null>(null);const[error,setError]=useState<unknown>(null);const[retry,setRetry]=useState(0);const[cancelling,setCancelling]=useState(false);useEffect(()=>{if(!id)return;let active=true;let timer:ReturnType<typeof setTimeout>;setJob(null);setError(null);const poll=async()=>{try{const j=await api.get<Job>(`/jobs/${id}`);if(!active)return;setJob(j);setError(null);if(['succeeded','failed','cancelled'].includes(j.state)){onDone();}else timer=setTimeout(poll,1500);}catch(e){if(active)setError(e);}};void poll();return()=>{active=false;clearTimeout(timer);};},[id,retry]);if(!id)return null;return <Panel title="작업 진행 상태" aside={job&&<Status value={job.state}/>}><ErrorNotice error={error} retry={()=>setRetry(n=>n+1)}/>{!job&&!error?<p>작업을 확인하고 있습니다…</p>:job&&<><div className="progress-meta"><span>{job.stage||'작업 대기'} · {show(job.completed)} / {show(job.total)}</span><span>{job.progress==null?'진행률 확인 중':`${Math.round(job.progress*100)}%`}</span></div><progress max="1" value={job.progress??undefined}/>{job.error&&<ErrorNotice error={typeof job.error==='object'&&job.error!==null&&'message'in job.error?job.error.message:show(job.error)}/>}<small className="muted mono">{id}</small>{['queued','running'].includes(job.state)&&<button className="danger" disabled={cancelling||job.cancel_requested} onClick={async()=>{setCancelling(true);try{await api.post(`/jobs/${id}/cancel`,{});setJob({...job,cancel_requested:true});}catch(e){setError(e);}finally{setCancelling(false);}}}>{job.cancel_requested?'취소 요청됨':'작업 취소'}</button>}</>}</Panel>;}


export function PlotArtifacts({items}:{items?:Artifact[]}){const plots=items?.filter(a=>a.media_type==='image/png'||a.kind==='png'||a.filename.toLowerCase().endsWith('.png'))||[];return plots.length?<div className="plot-artifacts">{plots.map(a=><figure key={a.id}><a href={a.download_url||`/api/v1/artifacts/${a.id}/download`} target="_blank" rel="noreferrer"><img src={a.download_url||`/api/v1/artifacts/${a.id}/download`} alt={`분석 결과 그래프: ${a.filename}`} loading="lazy"/></a><figcaption>{a.filename} · 서버에서 계산한 결과 <a href={a.download_url||`/api/v1/artifacts/${a.id}/download`} download>원본 다운로드 ↓</a></figcaption></figure>)}</div>:null;}
