import {useEffect,useState,type ReactNode} from 'react';
import {api,ApiError,type Artifact,type Job,type PpaSummary,type Row} from './lib/api';
export const show=(v:unknown):string=>v===null||v===undefined?'—':typeof v==='object'?JSON.stringify(v):String(v);
export const errorText=(error:unknown)=>error instanceof Error?error.message:typeof error==='object'&&error!==null&&'message'in error?String(error.message):show(error);
export function ErrorNotice({error,retry}:{error:unknown;retry?:()=>void}){return error?<div role="alert" className="notice error"><strong>요청을 완료하지 못했습니다.</strong><div>{errorText(error)}</div>{error instanceof ApiError&&error.field&&<small>입력 항목: {error.field}</small>}{error instanceof ApiError&&error.requestId&&<small>요청 ID: {error.requestId}</small>}{retry&&<button type="button" onClick={retry}>다시 시도</button>}</div>:null;}
export function useResource<T>(path:string|null){const[data,setData]=useState<T|null>(null);const[error,setError]=useState<unknown>(null);const[loading,setLoading]=useState(false);const[tick,setTick]=useState(0);useEffect(()=>{if(!path){setData(null);return;}let active=true;setData(null);setLoading(true);setError(null);api.get<T>(path).then(v=>{if(active)setData(v);}).catch(e=>{if(active)setError(e);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[path,tick]);return{data,error,loading,reload:()=>setTick(n=>n+1)};}
export function Heading({eyebrow,title,children}:{eyebrow:string;title:string;children?:ReactNode}){return <header className="page-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{children&&<p>{children}</p>}</header>;}
export function Panel({title,children,aside}:{title:string;children:ReactNode;aside?:ReactNode}){return <section className="panel"><div className="panel-heading"><h2>{title}</h2>{aside}</div>{children}</section>;}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function Status({value}:{value:string}){return <span className={'status '+value}>{({queued:'대기',running:'실행 중',succeeded:'완료',failed:'실패',cancelled:'취소',draft:'초안',published:'발행',partial:'부분 완료',skipped:'건너뜀',invalid:'유효하지 않음',drafting:'작성 중',temporary:'임시 결과',saved:'저장됨',discarded:'폐기됨',blocked:'차단됨'} as Record<string,string>)[value]||value}</span>;}
export function JsonDetails({title,value,open=false}:{title:string;value:unknown;open?:boolean}){return <details open={open}><summary>{title}</summary><pre>{JSON.stringify(value,null,2)}</pre></details>;}
export function DataTable({rows,columns,caption}:{rows:Row[];columns?:string[];caption?:string}){const[limit,setLimit]=useState(100);const keys=columns||Array.from(new Set(rows.flatMap(Object.keys)));if(!rows.length)return <p className="empty">표시할 데이터가 없습니다.</p>;return <><div className="table-scroll"><table>{caption&&<caption>{caption}</caption>}<thead><tr>{keys.map(k=><th key={k} scope="col">{k}</th>)}</tr></thead><tbody>{rows.slice(0,limit).map((row,i)=><tr key={i}>{keys.map(k=><td key={k} title={show(row[k])}>{show(row[k])}</td>)}</tr>)}</tbody></table></div>{rows.length>limit&&<button className="subtle" type="button" onClick={()=>setLimit(n=>n+100)}>100행 더 보기 ({Math.min(limit,rows.length)}/{rows.length})</button>}</>;}
export function Notices({items,title='경고 및 안내'}:{items?:unknown[];title?:string}){if(!items?.length)return null;return <div className="notice"><strong>{title}</strong><ul>{items.map((item,i)=><li key={i}>{show(item)}</li>)}</ul></div>;}
// Worker stage names as reported by the job; counts come straight from the job record.
const stageLabels:Record<string,string>={queued:'대기 중',parsing:'데이터 읽는 중',download:'데이터 준비 중',training:'모델 학습 중',inference:'추론 실행 중',exporting:'결과 저장 중',succeeded:'완료',failed:'실패',cancelled:'취소됨'};
const eng=(v:number|null|undefined,unit:string,scale=1)=>v==null?'—':`${(v*scale).toPrecision(4)} ${unit}`;
const area=(v?:number|null)=>v==null?'—':`${(v*1e12).toFixed(1)} µm²`;
const energy=(v?:number|null)=>v==null?'—':`${(v*1e12).toFixed(2)} pJ`;
const seconds=(v?:number|null)=>v==null?'—':v<1e-9?`${(v*1e12).toFixed(2)} ps`:v<1e-6?`${(v*1e9).toFixed(2)} ns`:`${(v*1e6).toFixed(3)} µs`;
const componentNames:Record<string,string>={cell_arrays:'셀 배열 (두 plane)',row_drivers_and_column_mux:'행 구동·열 mux (plane별)',column_read_and_sensing:'열 읽기·감지(MLSA, plane별)',digital_subtractor:'디지털 뺄셈기',shift_add_accumulate:'시프트-가산 누산(1회)',pe_tile_chip_periphery:'PE·타일·칩 공유 회로',input_output_buffers:'입출력 버퍼',interconnect:'연결망',leakage:'누설(창 보정 시간 기준)'};
const unknownNames:Record<string,string>={adc_range_scaling:'ADC 범위 스케일링',digital_bias_add:'디지털 bias 가산',analog_subtraction_frontend:'아날로그 차감 front end',signed_column_sensing:'부호 있는 열 감지·변환'};
const orderNames:Record<string,string>={adc_then_subtract:'개별 ADC 후 차감',subtract_then_adc:'차감 후 ADC'};
export function PpaPanel({ppa}:{ppa?:PpaSummary|null}){
 if(!ppa)return null;
 const total=ppa.known_total;const unknown=ppa.unknown_components||ppa.coverage?.missing_components||[];const comps=ppa.known_components||[];
 const inventory=ppa.coverage?.inventory;const placement=ppa.placement;const sched=ppa.schedule_check;const fid=ppa.fidelity;
 return <div className="ppa-panel"><div className="result-title"><h4>PPA (면적·에너지·지연) · 조건부 비용 추정</h4><Status value={ppa.status}/></div>
  <p className="muted">{ppa.label||'측정 전도도를 적용한 선형 등가 회로의 조건부 비용 추정입니다. 실제 제작 CTFM 가속기의 성능이 아닙니다.'}{ppa.model_status?<> 모델 상태 <code>{ppa.model_status}</code> · validated_for_ctfm {String(ppa.preset?.validated_for_ctfm??false)}{ppa.order?` · ADC 순서 ${orderNames[ppa.order]||ppa.order}`:''}</>:null}</p>
  {ppa.candidate?<p className="notice">PPA 평가 대상: {ppa.candidate.profile_id} / revision {ppa.candidate.profile_revision} · {ppa.candidate.pool} · {ppa.candidate.mapping}. 첫 번째 유효 후보의 기준 시점 비용만 평가합니다. 다른 후보의 비용을 보려면 해당 후보만 선택해 실행하세요. D2D·C2C·Retention에 따른 비용 변화는 평가하지 않습니다.</p>:null}
  <Notices items={ppa.blocking_reasons?.length?ppa.blocking_reasons:undefined} title="PPA를 실행하지 못한 이유"/>
  {total?<div className="notice" role="status"><strong>완전한 PPA 값은 제공하지 않습니다 — 비용이 산정되지 않은 블록 {unknown.length}개가 있습니다.</strong>
   <DataTable caption="알려진 블록의 합계 (미산정 블록은 0이 아니라 포함되지 않음 · 상한도 하한도 아님)" rows={[{'면적':area(total.area_m2),'추론당 에너지':total.energy_j_per_inference==null?'— (산정 불가)':energy(total.energy_j_per_inference),'추론당 지연(읽기 창 보정)':total.latency_s_per_inference==null?'— (산정 불가)':seconds(total.latency_s_per_inference),'완전한 값':String(total.complete)}]}/>
   <small>{total.note}</small></div>
   :<Notices items={ppa.incomplete_reasons?.length?ppa.incomplete_reasons:(ppa.blocking_reasons?undefined:ppa.reasons)} title="총계를 제공하지 않는 이유 · 실행 여부와 별개"/>}
  {unknown.length?<DataTable caption="비용이 산정되지 않은 블록 · 근거가 있는 모델이 생기기 전까지 총계는 null입니다" rows={unknown.map(u=>({블록:unknownNames[u.id]||u.id,이유:('detail' in u?u.detail:'')}))}/>:null}
  {comps.length?<DataTable caption="산정된 블록 · 소유자별 집계(plane별 회로는 두 plane 합, 공유 회로는 한 번)" rows={comps.map(c=>({블록:componentNames[c.id]||c.id,소유:c.owner==='per_plane'?'plane별':'공유',면적:area(c.area_m2),'추론당 에너지':energy(c.energy_j_per_inference),설명:c.note||''}))}/>:null}
  {placement?<DataTable caption="셀 배치 · 명세 타일링과 엔진 배치(빈 슬롯은 짓지 않음)" rows={[{'배열 크기':placement.tile_size??null,'plane당 명세 subarray':placement.spec_slots_per_plane??null,'plane당 사용 subarray':placement.used_slots_per_plane??null,'엔진 슬롯(제거 전)':placement.instantiated_slots_per_plane??null,'plane당 가중치 셀':placement.weight_cells_per_plane??null,'물리 셀(두 plane)':placement.physical_cells??null,'빈 셀':placement.padding_cells??null,'명세 타일링과 일치':String(placement.matches_spec_tiling)}]}/>:null}
  {sched?<div className={'notice'+(sched.status==='infeasible'?' error':'')} role="status"><strong>시간 검사 · 읽기 창 {seconds(sched.read_window_s)}: {sched.status==='feasible'?'성립':sched.status==='infeasible'?'미성립':'미수행'}</strong><div>{sched.detail||'—'}</div>
   {sched.engine_clock_period_s!=null?<small>엔진 클럭 {seconds(sched.engine_clock_period_s)} · 열 정착 {seconds(sched.bitline_settling_s)} · 사이클/추론 {sched.cycles_per_inference?.toFixed(0)??'—'} · 엔진 원시 지연 {seconds(ppa.diagnostics?.latency?.engine_clock_s)}</small>:null}</div>:null}
  {fid?<div className={'notice'+(fid.status==='passed'?'':' error')} role="status"><strong>모델 정합성 검사(엔진 종료 코드와 별개): {fid.status==='passed'?'통과':'실패'}</strong><div>{fid.meaning}</div>
   <DataTable rows={fid.layers.map(l=>({층:l.layer,'열 전도도 상대 오차(+/-)':`${l.column_conductance_rel_error.plus.toExponential(1)} / ${l.column_conductance_rel_error.minus.toExponential(1)}`,'읽은 행':`${l.rows_read} / ${l.rows_read_expected}`,'가중치 셀':`${l.weight_cells} / ${l.weight_cells_expected}`,'사용 subarray':`${l.used_slots} / ${l.used_slots_expected}`}))}/></div>:null}
  {ppa.input_encoding?<p className="muted">입력: {ppa.input_encoding.input} · {ppa.input_encoding.schedule}. 전도도: {ppa.conductance&&'transfer' in ppa.conductance?String(ppa.conductance.transfer):'—'}. 표본: {ppa.trace_sample||'—'}.</p>:null}
  {inventory?<DataTable caption="명세 산술 목록(가중치 셀×2, 패딩·엔진 배치 제외) · 위 셀 배치와 다를 수 있음" rows={[{'변환 순서':inventory.adc_order??null,'물리 셀 수':inventory.physical_cells??null,'ADC 수':inventory.adc_count??null,'추론당 변환 cycle':inventory.conversion_cycles_per_inference??null,'입력 정밀도':String(inventory.input_bits??'—')+' bit'}]}/>:null}
  {ppa.coverage?.excluded_by_scope?.length?<DataTable caption="범위에서 제외한 항목" rows={ppa.coverage.excluded_by_scope.map(m=>({항목:m.id,내용:m.detail}))}/>:null}
  {ppa.engine_totals?<DataTable caption="엔진 원시 값(진단) · 위 미산정 블록을 포함하지 않으므로 전체 PPA가 아닙니다" rows={[ppa.engine_totals as Row]}/>:null}
  {ppa.adc_range_note?<DataTable caption="ADC 범위: 정확도 모델의 범위 R과 엔진 기준 전류 범위(전체 스케일)의 비" rows={Object.entries(ppa.adc_range_note).map(([layer,v])=>({층:layer,'정확도 범위 R (S)':v.accuracy_range_s??null,'엔진 전체 스케일 (S)':v.engine_full_scale_s,비율:v.fraction==null?null:v.fraction.toFixed(4)}))}/>:null}
  {ppa.preset?.preset_id?<p className="muted">preset <code>{ppa.preset.preset_id}</code>{ppa.preset_artifact?.sha256?` · ${ppa.preset_artifact.sha256.slice(0,12)}`:''}{ppa.build?.binary?` · 엔진 빌드 ${String(ppa.build.binary).slice(-12)}`:''}</p>:null}
  {ppa.model_mismatches?.length?<DataTable caption="정확도 모델과 PPA 엔진 모델의 차이 · 남은 가정" rows={ppa.model_mismatches.map(m=>({id:m.id,내용:m.detail}))}/>:null}
  <JsonDetails title="PPA 상세 · 엔진 빌드 · 검사 원자료 (내보내기 파일: ppa-*.json)" value={ppa}/></div>;
}
// Only result tables/graphs (role=user) are offered; checkpoints, arrays and diagnostics stay on the server.
// Artifacts registered before roles existed carry no role and are treated as internal, except the
// single legacy graph (plot.png), which PlotArtifacts still shows.
export const userArtifacts=(items?:Artifact[])=>(items||[]).filter(a=>a.role==='user');
export function Downloads({items,empty='다운로드할 결과 파일이 없습니다.'}:{items?:Artifact[];empty?:string}){const files=userArtifacts(items);return files.length?<div className="downloads">{files.map(a=><a key={a.id} href={a.download_url||`/api/v1/artifacts/${a.id}/download`} download>{a.filename}<span aria-hidden>↓</span></a>)}</div>:<p className="muted">{empty}</p>;}
export function JobProgress({id,onDone}:{id:string|null;onDone:()=>void}){const[job,setJob]=useState<Job|null>(null);const[error,setError]=useState<unknown>(null);const[retry,setRetry]=useState(0);const[cancelling,setCancelling]=useState(false);useEffect(()=>{if(!id)return;let active=true;let timer:ReturnType<typeof setTimeout>;setJob(null);setError(null);const poll=async()=>{try{const j=await api.get<Job>(`/jobs/${id}`);if(!active)return;setJob(j);setError(null);if(['succeeded','failed','cancelled'].includes(j.state)){onDone();}else timer=setTimeout(poll,1500);}catch(e){if(active)setError(e);}};void poll();return()=>{active=false;clearTimeout(timer);};},[id,retry]);if(!id)return null;return <Panel title="작업 진행 상태" aside={job&&<Status value={job.state}/>}><ErrorNotice error={error} retry={()=>setRetry(n=>n+1)}/>{!job&&!error?<p>작업을 확인하고 있습니다…</p>:job&&<><div className="progress-meta"><span>{stageLabels[job.stage||'']||job.stage||'대기'}{job.total?` · ${show(job.completed)} / ${show(job.total)}`:''}</span><span className="muted">단계별 진행 · 전체 남은 시간은 추정하지 않음</span></div>{/* No count yet (e.g. training) = indeterminate bar, never an invented percentage. */}<progress max="1" value={job.total?(job.completed||0)/job.total:undefined}/>{job.error&&<ErrorNotice error={typeof job.error==='object'&&job.error!==null&&'message'in job.error?job.error.message:show(job.error)}/>}{['queued','running'].includes(job.state)&&<button className="danger" disabled={cancelling||job.cancel_requested} onClick={async()=>{setCancelling(true);try{await api.post(`/jobs/${id}/cancel`,{});setJob({...job,cancel_requested:true});}catch(e){setError(e);}finally{setCancelling(false);}}}>{job.cancel_requested?'취소 요청됨':'작업 취소'}</button>}</>}</Panel>;}


export function PlotArtifacts({items}:{items?:Artifact[]}){const plots=(items||[]).filter(a=>a.filename.toLowerCase().endsWith('.png')&&(a.role==='user'||(!a.role&&a.filename==='plot.png')));return plots.length?<div className="plot-artifacts">{plots.map(a=><figure key={a.id}><img src={a.download_url||`/api/v1/artifacts/${a.id}/download`} alt={`분석 결과 그래프: ${a.filename}`} loading="lazy"/><figcaption>{a.filename} · 서버 계산 결과</figcaption></figure>)}</div>:null;}
