import {useState} from 'react';
import {api} from '../../lib/api';
import type {Comparison} from '../../lib/workflows';
import {ErrorNotice,Heading,Panel,Status,useResource} from '../../shared';
import {ComparisonResults} from './Comparison';

export function SavedResults(){const saved=useResource<{items:Comparison[]}>('/comparisons?scope=saved'),temporary=useResource<{items:Comparison[]}>('/comparisons?scope=temporary');const[id,setId]=useState<string|null>(new URLSearchParams(location.search).get('comparison')),[error,setError]=useState<unknown>(null),[busy,setBusy]=useState(false);const selected=useResource<Comparison>(id?`/comparisons/${id}`:null);const[cloneOp,setCloneOp]=useState<string|null>(null);
 const clone=async()=>{if(!id)return;setBusy(true);setError(null);const operation=cloneOp||crypto.randomUUID();setCloneOp(operation);try{const r=await api.cloneComparison(id,operation);location.href=`/simulator?comparison=${r.comparison_id}`;}catch(e){setError(e);}finally{setBusy(false);}};
 const discard=async(target:string)=>{setBusy(true);setError(null);try{await api.discardComparison(target);temporary.reload();if(id===target)setId(null);}catch(e){setError(e);}finally{setBusy(false);}};
 return <><Heading eyebrow="SAVED RESULTS" title="저장한 결과">이름 붙인 비교와 다시 이어서 할 임시 작업을 따로 엽니다.</Heading><ErrorNotice error={error}/><div className="two-columns"><Panel title="저장한 비교" aside={<button onClick={saved.reload}>새로고침</button>}><ErrorNotice error={saved.error} retry={saved.reload}/>{!saved.data?.items.length&&<p className="empty">저장한 비교가 없습니다.</p>}{saved.data?.items.map(r=><p key={r.comparison_id}><button type="button" onClick={()=>{setId(r.comparison_id);history.replaceState(null,'',`/saved-results?comparison=${r.comparison_id}`);}}>{r.name||r.comparison_id}</button> · <Status value={r.outcome||r.lifecycle}/> · {r.cards.length}개 카드</p>)}</Panel><Panel title="임시 작업" aside={<button onClick={temporary.reload}>새로고침</button>}><ErrorNotice error={temporary.error} retry={temporary.reload}/>{!temporary.data?.items.length&&<p className="empty">임시 작업이 없습니다.</p>}{temporary.data?.items.map(r=><p key={r.comparison_id}><a href={`/simulator?comparison=${r.comparison_id}`}>{r.name||r.comparison_id.slice(0,8)} · 이어서 열기</a> · <Status value={r.lifecycle}/> <button disabled={busy} onClick={()=>void discard(r.comparison_id)}>폐기</button></p>)}</Panel></div>{selected.data&&<><ComparisonResults record={selected.data}/><Panel title="이 결과에서 다시 실행"><button disabled={busy} onClick={()=>void clone()}>새 임시 비교로 복제</button></Panel></>}</>;
}
